### ISSUE TITLE
Version of python modules used to generate models.

### ISSUE THREAD

**Issue by gouthamatla** [ohlerlab/DeepRiPe#4]
Hi All,

I would like to know which version of different python modules were used to train the models. When I am trying to run the example notebooks, I am getting some errors/warnings like

> - module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'
> - module 'tensorflow' has no attribute 'placeholder'
> - /rds/general/user/gatla/home/softs/DeepRiPe/Scripts/plotseqlogo.py:44: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.

Most likely these errors are due to different versions of python modules I am uisng.

**Comment by sakshimisra** [comment]
@gouthamatla were you able to resolve the issue ?
